version: '3.7'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:dockdock@db:5444/postgres
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dockdock
      POSTGRES_DB: postgres
    image: postgres:12
    networks:
      - default
    ports:
      - 5444:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data